"""Generate the Figure 2 benchmark-construction example.

Submission figures 1, 3, 4, and 5 are generated by ``submission_figures.py``.
This entrypoint is intentionally limited to Figure 2 so it cannot overwrite the
redesigned result figures.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import replace
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import yaml
from matplotlib import gridspec

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.data.irreversible_source_inference import (  # noqa: E402
    IrreversibleSourceConfig,
    generate_irreversible_source_splits,
)

TEXT = "#1F2933"
MUTED_TEXT = "#5B6470"
CORE_COLOR = np.asarray([0.05, 0.55, 0.50])
NUISANCE_COLOR = np.asarray([0.81, 0.38, 0.28])


def configure_style() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": 150,
            "savefig.dpi": 400,
            "font.family": "DejaVu Sans",
            "font.size": 8,
            "axes.titlesize": 8.5,
            "axes.labelsize": 8,
            "xtick.labelsize": 7,
            "ytick.labelsize": 7,
            "axes.linewidth": 0.6,
            "text.color": TEXT,
            "xtick.color": TEXT,
            "ytick.color": TEXT,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def load_data_config(path: Path) -> IrreversibleSourceConfig:
    with path.open("r", encoding="utf-8") as f:
        raw = yaml.safe_load(f) or {}
    data = raw.get("data", raw)
    allowed = set(IrreversibleSourceConfig.__dataclass_fields__)
    data = {k: v for k, v in data.items() if k in allowed}
    return IrreversibleSourceConfig(**data)


def save_figure(fig: plt.Figure, out_dir: Path, name: str) -> None:
    figure_dir = out_dir / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(figure_dir / f"{name}.pdf", bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def normalize_image(img: np.ndarray, vmax: float | None = None) -> np.ndarray:
    img = np.asarray(img, dtype=float)
    img = np.clip(img, 0.0, None)
    if vmax is None:
        vmax = float(np.quantile(img, 0.995))
    vmax = max(vmax, 1e-8)
    return np.clip(img / vmax, 0.0, 1.0)


def smooth_image(img: np.ndarray, passes: int = 1) -> np.ndarray:
    out = np.asarray(img, dtype=float)
    kernel = np.asarray([[1.0, 2.0, 1.0], [2.0, 4.0, 2.0], [1.0, 2.0, 1.0]]) / 16.0
    for _ in range(passes):
        padded = np.pad(out, 1, mode="edge")
        out = (
            kernel[0, 0] * padded[:-2, :-2]
            + kernel[0, 1] * padded[:-2, 1:-1]
            + kernel[0, 2] * padded[:-2, 2:]
            + kernel[1, 0] * padded[1:-1, :-2]
            + kernel[1, 1] * padded[1:-1, 1:-1]
            + kernel[1, 2] * padded[1:-1, 2:]
            + kernel[2, 0] * padded[2:, :-2]
            + kernel[2, 1] * padded[2:, 1:-1]
            + kernel[2, 2] * padded[2:, 2:]
        )
    return out


def colorize(img: np.ndarray, color: np.ndarray, vmax: float, gamma: float = 0.62) -> np.ndarray:
    norm = normalize_image(smooth_image(img, passes=1), vmax=vmax)
    norm = np.power(norm, gamma)
    return norm[..., None] * color[None, None, :]


def channel_frame(arr: np.ndarray, t: int, channel: int) -> np.ndarray:
    frame = arr[t]
    if frame.ndim == 3:
        return np.clip(frame[channel], 0.0, None)
    return np.clip(frame, 0.0, None)


def composite_frame(arr: np.ndarray, t: int, core_vmax: float, nuisance_vmax: float) -> np.ndarray:
    frame = arr[t]
    if frame.ndim == 3:
        core = colorize(frame[0], CORE_COLOR, core_vmax)
        nuisance = colorize(frame[1], NUISANCE_COLOR, nuisance_vmax)
        return np.clip(core + nuisance, 0.0, 1.0)
    return np.clip(colorize(frame, CORE_COLOR, core_vmax), 0.0, 1.0)


def figure_benchmark(out_dir: Path, config_path: Path) -> None:
    config = load_data_config(config_path)
    config = replace(
        config,
        n_train=64,
        n_val_iid=16,
        n_iid_test=16,
        n_ood_test=64,
        seed=19,
    )
    splits = generate_irreversible_source_splits(config)
    train = splits["train"]
    ood = splits["ood_test"]
    idx = int(np.where(train.y == 1)[0][0])
    idx_ood = int(np.where(ood.y == 1)[0][0])
    times = list(range(config.length))

    fig = plt.figure(figsize=(7.55, 3.55))
    grid = gridspec.GridSpec(
        5,
        1 + len(times),
        figure=fig,
        width_ratios=[1.25] + [1] * len(times),
        hspace=0.075,
        wspace=0.045,
        left=0.015,
        right=0.998,
        top=0.945,
        bottom=0.02,
    )
    rows = [
        ("A", "Core source", "causal trace", train.core_only[idx], "core"),
        ("B", "Nuisance arrow", "shortcut", train.nuisance_only[idx], "nuisance"),
        ("C", "Mixed input", "train/IID", train.mixed[idx], "mixed"),
        ("D", "Counterfactual", "core fixed", train.counterfactual[idx], "mixed"),
        ("E", "OOD input", "arrow shifted", ood.mixed[idx_ood], "mixed"),
    ]
    core_stack = [
        train.core_only[idx],
        train.mixed[idx][:, 0],
        train.counterfactual[idx][:, 0],
        ood.mixed[idx_ood][:, 0],
    ]
    nuisance_stack = [
        train.nuisance_only[idx],
        train.mixed[idx][:, 1],
        train.counterfactual[idx][:, 1],
        ood.mixed[idx_ood][:, 1],
    ]
    core_vmax = max(float(np.quantile(arr, 0.995)) for arr in core_stack)
    nuisance_vmax = max(float(np.quantile(arr, 0.995)) for arr in nuisance_stack)

    for r, (label, row_name, sublabel, seq, mode) in enumerate(rows):
        ax_label = fig.add_subplot(grid[r, 0])
        ax_label.set_axis_off()
        ax_label.text(0.02, 0.64, label, fontsize=8.2, fontweight="bold", color=TEXT)
        ax_label.text(0.18, 0.64, row_name, fontsize=6.8, fontweight="bold", ha="left", color=TEXT)
        ax_label.text(0.18, 0.30, sublabel, fontsize=5.8, color=MUTED_TEXT, ha="left")
        for c, t in enumerate(times):
            ax = fig.add_subplot(grid[r, c + 1])
            if mode == "core":
                img = colorize(channel_frame(seq, t, 0), CORE_COLOR, core_vmax)
            elif mode == "nuisance":
                img = colorize(channel_frame(seq, t, 0), NUISANCE_COLOR, nuisance_vmax)
            else:
                img = composite_frame(seq, t, core_vmax, nuisance_vmax)
            ax.imshow(np.clip(img, 0.0, 1.0), interpolation="bicubic")
            ax.set_xticks([])
            ax.set_yticks([])
            for spine in ax.spines.values():
                spine.set_linewidth(0.35)
                spine.set_color("#D6DADE")
            if r == 0:
                ax.set_title(f"t={t}", pad=2.5, fontsize=5.9, color=MUTED_TEXT)

    save_figure(fig, out_dir, "fig02_benchmark_construction")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=Path("configs/irreversible_source_main.yaml"))
    parser.add_argument("--out-dir", type=Path, default=Path("paper/neurocomputing"))
    args = parser.parse_args()

    configure_style()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    figure_benchmark(args.out_dir, args.config)


if __name__ == "__main__":
    main()
